[package]
name = "nockchain-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.35", features = ["process", "time"] }
env_logger = "0.10"
log = "0.4"
regex = "1.9"
dotenvy = "0.15"